framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAIL_USER)%'
        headers:
            from: 'Beya Barkous (NE PAS RÉPONDRE) <%env(MAIL_USER)%>'
